// Intentionally independent from performance-track-record-model.mjs so a
// production contract edit cannot make its own contract check pass by construction.
export const PERFORMANCE_TRACK_CONTRACT_FIELDS = [
  "Run Key",
  "Run ID",
  "Run Attempt",
  "Job ID",
  "Workflow",
  "Teable EE Ref",
  "Commit SHA",
  "Case ID",
  "Case Title",
  "Engine",
  "Result",
  "Started At",
  "Finished At",
  "Duration Ms",
  "Threshold Passed",
  "Primary Metric",
  "Primary Metric Value",
  "Primary Threshold",
  "Trace Ref Count",
  "Saved Trace Count",
  "Failed Trace Count",
  "Artifact Name",
  "Artifact URL",
  "Run URL",
  "Trace URL",
  "Manifest Path",
  "Metrics JSON",
  "Thresholds JSON",
  "Phases JSON",
  "Trace Manifest JSON",
  "Summary Markdown",
  "Error",
].map((name) => ({ name }));
